name: 1.19.2 Auto Build

on:
  push:
    branches:
      - '1.19.2'
    paths:
      - 'gradle.properties'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build publish

      - name: Upload Jars
        uses: actions/upload-artifact@v3
        with:
          name: GTLib
          path: |
            fabric/build/libs/
            forge/build/libs/